version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.firebase:firebase-config
    versions:
    - 20.0.3
  - dependency-name: com.google.android.play:core
    versions:
    - 1.9.1
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: androidx.appcompat:appcompat
    versions:
    - 1.3.0-beta01
  - dependency-name: com.google.firebase:firebase-messaging
    versions:
    - 21.0.1
